name: mpos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  intl: ^0.20.2
  syncfusion_flutter_charts: ^30.1.42
  csv: ^6.0.0
  path_provider: ^2.0.11
  file_picker: ^10.2.0
  http: ^1.2.1
  url_launcher: ^6.1.5
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  json_serializable: ^6.8.0

  json_annotation: any
  path: any
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  connectivity_plus: ^6.0.3
  permission_handler: ^12.0.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/discounts.json
    - assets/expiration-dates.json
    - assets/packages.json
    - assets/products.json