name: mpos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.1
  objectbox_flutter_libs: any

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.1.40
  csv: ^6.0.0
  path_provider: ^2.0.11
  file_picker: ^8.0.5
  http: ^1.2.1
  url_launcher: ^6.1.5
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  json_serializable: ^6.8.0

  json_annotation: any
  path: any
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/discounts.json
    - assets/expiration-dates.json
    - assets/packages.json
    - assets/products.json